/**
 * Phase 3B activity type registry — 11 supported contextual actions.
 */

import type {
  ActivityCardEligibilityInput,
  ActivityCardTypeDefinition,
} from './activity-card-contract';
import { ACTIVITY_CARD_TYPES } from './activity-card-contract';

export const ACTIVITY_CARD_TYPE_REGISTRY: Record<
  (typeof ACTIVITY_CARD_TYPES)[number],
  ActivityCardTypeDefinition
> = {
  PROFILE_COMPLETION: {
    type: 'PROFILE_COMPLETION',
    priority: 100,
    titleKey: 'activityCards.types.profileCompletion.title',
    descriptionKey: 'activityCards.types.profileCompletion.description',
    icon: 'UserCircle',
    actionLabelKey: 'activityCards.types.profileCompletion.action',
    actionHref: '/profile',
    dismissible: true,
    cooldownDays: 7,
    ctaKind: 'navigate',
    isEligible: (i) => i.loggedIn && i.completenessPercent < 100,
    eligibilityReason: () => 'profile_incomplete',
  },
  REQUEST_REVIEW: {
    type: 'REQUEST_REVIEW',
    priority: 95,
    titleKey: 'activityCards.types.requestReview.title',
    descriptionKey: 'activityCards.types.requestReview.description',
    icon: 'Star',
    actionLabelKey: 'activityCards.types.requestReview.action',
    actionHref: '/orders',
    dismissible: true,
    cooldownDays: 3,
    ctaKind: 'navigate',
    isEligible: (i) => i.loggedIn && i.completedDealWithoutReview,
    eligibilityReason: () => 'completed_deal_without_review',
  },
  SHARE_QR: {
    type: 'SHARE_QR',
    priority: 60,
    titleKey: 'activityCards.types.shareQr.title',
    descriptionKey: 'activityCards.types.shareQr.description',
    icon: 'QrCode',
    actionLabelKey: 'activityCards.types.shareQr.action',
    actionHref: '/profile',
    dismissible: true,
    cooldownDays: 14,
    ctaKind: 'open_share_sheet',
    isEligible: (i) => i.loggedIn && Boolean(i.profileImage),
    eligibilityReason: () => 'profile_ready_for_share',
  },
  NEARBY_HELP_REQUEST: {
    type: 'NEARBY_HELP_REQUEST',
    priority: 85,
    titleKey: 'activityCards.types.nearbyHelp.title',
    descriptionKey: 'activityCards.types.nearbyHelp.description',
    icon: 'HandHeart',
    actionLabelKey: 'activityCards.types.nearbyHelp.action',
    actionHref: '/?chip=sale',
    dismissible: true,
    cooldownDays: 7,
    ctaKind: 'navigate',
    isEligible: (i) =>
      i.loggedIn && i.hasLocation && i.nearbyRequestCount > 0,
    eligibilityReason: () => 'nearby_requests_available',
  },
  UPLOAD_FIRST_LISTING: {
    type: 'UPLOAD_FIRST_LISTING',
    priority: 90,
    titleKey: 'activityCards.types.uploadListing.title',
    descriptionKey: 'activityCards.types.uploadListing.description',
    icon: 'PackagePlus',
    actionLabelKey: 'activityCards.types.uploadListing.action',
    actionHref: '/sell/new',
    dismissible: true,
    cooldownDays: 7,
    ctaKind: 'open_create_flow',
    isEligible: (i) =>
      i.loggedIn && i.hasSellerRole && i.productCount === 0,
    eligibilityReason: () => 'no_listings',
  },
  UPLOAD_FIRST_INSPIRATION: {
    type: 'UPLOAD_FIRST_INSPIRATION',
    priority: 70,
    titleKey: 'activityCards.types.uploadInspiration.title',
    descriptionKey: 'activityCards.types.uploadInspiration.description',
    icon: 'Sparkles',
    actionLabelKey: 'activityCards.types.uploadInspiration.action',
    actionHref: '/sell/new',
    dismissible: true,
    cooldownDays: 7,
    ctaKind: 'open_create_flow',
    isEligible: (i) => i.loggedIn && i.dishCount === 0,
    eligibilityReason: () => 'no_inspiration_posts',
  },
  COMPLETE_WORKSPACE: {
    type: 'COMPLETE_WORKSPACE',
    priority: 75,
    titleKey: 'activityCards.types.completeWorkspace.title',
    descriptionKey: 'activityCards.types.completeWorkspace.description',
    icon: 'Images',
    actionLabelKey: 'activityCards.types.completeWorkspace.action',
    actionHref: '/profile',
    dismissible: true,
    cooldownDays: 14,
    ctaKind: 'navigate',
    isEligible: (i) =>
      i.loggedIn && i.hasSellerRole && !i.hasWorkspacePhotos,
    eligibilityReason: () => 'workspace_photos_missing',
  },
  VERIFY_ACCOUNT: {
    type: 'VERIFY_ACCOUNT',
    priority: 98,
    titleKey: 'activityCards.types.verifyAccount.title',
    descriptionKey: 'activityCards.types.verifyAccount.description',
    icon: 'ShieldCheck',
    actionLabelKey: 'activityCards.types.verifyAccount.action',
    actionHref: '/profile',
    dismissible: false,
    cooldownDays: 7,
    ctaKind: 'navigate',
    isEligible: (i) => i.loggedIn && !i.emailVerified,
    eligibilityReason: () => 'email_not_verified',
  },
  ADD_WORKSHOP: {
    type: 'ADD_WORKSHOP',
    priority: 65,
    titleKey: 'activityCards.types.addWorkshop.title',
    descriptionKey: 'activityCards.types.addWorkshop.description',
    icon: 'GraduationCap',
    actionLabelKey: 'activityCards.types.addWorkshop.action',
    actionHref: '/sell/new',
    dismissible: true,
    cooldownDays: 14,
    ctaKind: 'open_create_flow',
    isEligible: (i) =>
      i.loggedIn &&
      i.hasSellerRole &&
      i.productCount > 0 &&
      !i.hasWorkshopListing,
    eligibilityReason: () => 'no_workshop_listing',
  },
  BECOME_COURIER: {
    type: 'BECOME_COURIER',
    priority: 55,
    titleKey: 'activityCards.types.becomeCourier.title',
    descriptionKey: 'activityCards.types.becomeCourier.description',
    icon: 'Truck',
    actionLabelKey: 'activityCards.types.becomeCourier.action',
    actionHref: '/delivery/onboarding',
    dismissible: true,
    cooldownDays: 14,
    ctaKind: 'navigate',
    isEligible: (i) => i.loggedIn && !i.hasDeliveryProfile,
    eligibilityReason: () => 'courier_disabled',
  },
  INVITE_FRIEND: {
    type: 'INVITE_FRIEND',
    priority: 50,
    titleKey: 'activityCards.types.inviteFriend.title',
    descriptionKey: 'activityCards.types.inviteFriend.description',
    icon: 'UserPlus',
    actionLabelKey: 'activityCards.types.inviteFriend.action',
    actionHref: '/welkom',
    dismissible: true,
    cooldownDays: 14,
    ctaKind: 'navigate',
    isEligible: (i) => i.loggedIn,
    eligibilityReason: () => 'community_activation',
  },
};

export function listActivityCardTypeDefinitions(): ActivityCardTypeDefinition[] {
  return ACTIVITY_CARD_TYPES.map((type) => ACTIVITY_CARD_TYPE_REGISTRY[type]);
}
