/**
 * Activity Card taxonomy — Phase 3A canonical definitions.
 * Cards activate participation; they are NOT recommendations or ranked content.
 */

import type {
  ActivityCardCategory,
  ActivityCardDefinition,
  ActivityCardId,
} from './activity-card-types';

export const ACTIVITY_CARD_CATEGORIES: Record<
  ActivityCardCategory,
  { labelKey: string; description: string }
> = {
  social_activation: {
    labelKey: 'activityCards.categories.social',
    description: 'Drive connection — fans, conversations, sharing.',
  },
  trust_activation: {
    labelKey: 'activityCards.categories.trust',
    description: 'Build deal/product trust through reviews and responses.',
  },
  marketplace_activation: {
    labelKey: 'activityCards.categories.marketplace',
    description: 'Publish offers, workshops, respond to requests.',
  },
  delivery_activation: {
    labelKey: 'activityCards.categories.delivery',
    description: 'Delivery profile, offers, and requests.',
  },
  community_activation: {
    labelKey: 'activityCards.categories.community',
    description: 'Inspiration and neighbor engagement.',
  },
  profile_completion: {
    labelKey: 'activityCards.categories.profile',
    description: 'Complete profile, values, workspace, payments.',
  },
  local_activation: {
    labelKey: 'activityCards.categories.local',
    description: 'Location, nearby requests, local invites.',
  },
};

const ALL_SURFACES = [
  'home_feed',
  'feed_mobile_insert',
  'desktop_sidebar',
  'profile_owner',
  'messages_inbox',
] as const;

const FEED_SURFACES = [
  'home_feed',
  'feed_mobile_insert',
  'desktop_sidebar',
] as const;

export const ACTIVITY_CARD_REGISTRY: Record<
  ActivityCardId,
  ActivityCardDefinition
> = {
  share_qr_code: {
    id: 'share_qr_code',
    category: 'social_activation',
    titleKey: 'activityCards.share_qr_code.title',
    descriptionKey: 'activityCards.share_qr_code.description',
    ctaKey: 'activityCards.share_qr_code.cta',
    ctaKind: 'open_share_sheet',
    priority: 'normal',
    allowedSurfaces: ['profile_owner', 'desktop_sidebar', ...FEED_SURFACES],
    requiredTriggers: ['logged_in', 'has_profile_photo'],
  },
  start_conversation: {
    id: 'start_conversation',
    category: 'social_activation',
    titleKey: 'activityCards.start_conversation.title',
    descriptionKey: 'activityCards.start_conversation.description',
    ctaKey: 'activityCards.start_conversation.cta',
    ctaKind: 'open_conversation',
    ctaHref: '/messages',
    priority: 'high',
    allowedSurfaces: ['home_feed', 'feed_mobile_insert', 'messages_inbox'],
    requiredTriggers: ['logged_in', 'favorites_without_conversations'],
  },
  become_a_fan: {
    id: 'become_a_fan',
    category: 'social_activation',
    titleKey: 'activityCards.become_a_fan.title',
    descriptionKey: 'activityCards.become_a_fan.description',
    ctaKey: 'activityCards.become_a_fan.cta',
    ctaKind: 'navigate',
    priority: 'low',
    allowedSurfaces: FEED_SURFACES,
    requiredTriggers: ['logged_in', 'no_fans'],
  },
  invite_someone: {
    id: 'invite_someone',
    category: 'social_activation',
    titleKey: 'activityCards.invite_someone.title',
    descriptionKey: 'activityCards.invite_someone.description',
    ctaKey: 'activityCards.invite_someone.cta',
    ctaKind: 'navigate',
    ctaHref: '/welkom',
    priority: 'normal',
    allowedSurfaces: [...FEED_SURFACES, 'profile_owner'],
    requiredTriggers: ['logged_in'],
  },
  ask_for_review: {
    id: 'ask_for_review',
    category: 'trust_activation',
    titleKey: 'activityCards.ask_for_review.title',
    descriptionKey: 'activityCards.ask_for_review.description',
    ctaKey: 'activityCards.ask_for_review.cta',
    ctaKind: 'navigate',
    ctaHref: '/verkoper/orders',
    priority: 'high',
    allowedSurfaces: ['profile_owner', 'desktop_sidebar', 'home_feed'],
    requiredTriggers: ['logged_in', 'is_seller', 'has_listings', 'no_reviews_received'],
  },
  leave_review_after_deal: {
    id: 'leave_review_after_deal',
    category: 'trust_activation',
    titleKey: 'activityCards.leave_review_after_deal.title',
    descriptionKey: 'activityCards.leave_review_after_deal.description',
    ctaKey: 'activityCards.leave_review_after_deal.cta',
    ctaKind: 'navigate',
    ctaHref: '/orders',
    priority: 'critical',
    allowedSurfaces: [
      'home_feed',
      'feed_mobile_insert',
      'desktop_sidebar',
      'messages_thread',
    ],
    requiredTriggers: ['logged_in', 'completed_deal_without_review'],
  },
  respond_to_review: {
    id: 'respond_to_review',
    category: 'trust_activation',
    titleKey: 'activityCards.respond_to_review.title',
    descriptionKey: 'activityCards.respond_to_review.description',
    ctaKey: 'activityCards.respond_to_review.cta',
    ctaKind: 'navigate',
    ctaHref: '/profile',
    priority: 'high',
    allowedSurfaces: ['profile_owner', 'desktop_sidebar'],
    requiredTriggers: ['logged_in', 'is_seller', 'pending_review_request'],
  },
  publish_first_offer: {
    id: 'publish_first_offer',
    category: 'marketplace_activation',
    titleKey: 'activityCards.publish_first_offer.title',
    descriptionKey: 'activityCards.publish_first_offer.description',
    ctaKey: 'activityCards.publish_first_offer.cta',
    ctaKind: 'open_create_flow',
    priority: 'critical',
    allowedSurfaces: [...ALL_SURFACES],
    requiredTriggers: ['logged_in', 'has_seller_role', 'no_listings'],
  },
  create_first_workshop: {
    id: 'create_first_workshop',
    category: 'marketplace_activation',
    titleKey: 'activityCards.create_first_workshop.title',
    descriptionKey: 'activityCards.create_first_workshop.description',
    ctaKey: 'activityCards.create_first_workshop.cta',
    ctaKind: 'open_create_flow',
    priority: 'normal',
    allowedSurfaces: FEED_SURFACES,
    requiredTriggers: ['logged_in', 'has_seller_role', 'has_listings'],
  },
  respond_to_request: {
    id: 'respond_to_request',
    category: 'marketplace_activation',
    titleKey: 'activityCards.respond_to_request.title',
    descriptionKey: 'activityCards.respond_to_request.description',
    ctaKey: 'activityCards.respond_to_request.cta',
    ctaKind: 'navigate',
    ctaHref: '/',
    priority: 'high',
    allowedSurfaces: FEED_SURFACES,
    requiredTriggers: ['logged_in', 'nearby_requests_available'],
  },
  add_listing_media: {
    id: 'add_listing_media',
    category: 'marketplace_activation',
    titleKey: 'activityCards.add_listing_media.title',
    descriptionKey: 'activityCards.add_listing_media.description',
    ctaKey: 'activityCards.add_listing_media.cta',
    ctaKind: 'navigate',
    ctaHref: '/verkoper/dashboard',
    priority: 'normal',
    allowedSurfaces: ['profile_owner', 'desktop_sidebar'],
    requiredTriggers: ['logged_in', 'is_seller', 'has_listings'],
  },
  request_delivery: {
    id: 'request_delivery',
    category: 'delivery_activation',
    titleKey: 'activityCards.request_delivery.title',
    descriptionKey: 'activityCards.request_delivery.description',
    ctaKey: 'activityCards.request_delivery.cta',
    ctaKind: 'navigate',
    ctaHref: '/orders',
    priority: 'normal',
    allowedSurfaces: FEED_SURFACES,
    requiredTriggers: ['logged_in', 'has_listings'],
  },
  offer_delivery: {
    id: 'offer_delivery',
    category: 'delivery_activation',
    titleKey: 'activityCards.offer_delivery.title',
    descriptionKey: 'activityCards.offer_delivery.description',
    ctaKey: 'activityCards.offer_delivery.cta',
    ctaKind: 'navigate',
    ctaHref: '/delivery/dashboard',
    priority: 'normal',
    allowedSurfaces: ['desktop_sidebar', 'profile_owner'],
    requiredTriggers: ['logged_in', 'no_delivery_profile'],
  },
  complete_delivery_profile: {
    id: 'complete_delivery_profile',
    category: 'delivery_activation',
    titleKey: 'activityCards.complete_delivery_profile.title',
    descriptionKey: 'activityCards.complete_delivery_profile.description',
    ctaKey: 'activityCards.complete_delivery_profile.cta',
    ctaKind: 'navigate',
    ctaHref: '/delivery/onboarding',
    priority: 'high',
    allowedSurfaces: ['profile_owner', 'desktop_sidebar'],
    requiredTriggers: ['logged_in', 'has_delivery_profile'],
  },
  publish_inspiration: {
    id: 'publish_inspiration',
    category: 'community_activation',
    titleKey: 'activityCards.publish_inspiration.title',
    descriptionKey: 'activityCards.publish_inspiration.description',
    ctaKey: 'activityCards.publish_inspiration.cta',
    ctaKind: 'open_create_flow',
    priority: 'normal',
    allowedSurfaces: FEED_SURFACES,
    requiredTriggers: ['logged_in', 'no_inspiration_posts'],
  },
  engage_with_neighbor: {
    id: 'engage_with_neighbor',
    category: 'community_activation',
    titleKey: 'activityCards.engage_with_neighbor.title',
    descriptionKey: 'activityCards.engage_with_neighbor.description',
    ctaKey: 'activityCards.engage_with_neighbor.cta',
    ctaKind: 'navigate',
    ctaHref: '/',
    priority: 'low',
    allowedSurfaces: FEED_SURFACES,
    requiredTriggers: ['logged_in', 'has_location'],
  },
  complete_profile: {
    id: 'complete_profile',
    category: 'profile_completion',
    titleKey: 'activityCards.complete_profile.title',
    descriptionKey: 'activityCards.complete_profile.description',
    ctaKey: 'activityCards.complete_profile.cta',
    ctaKind: 'navigate',
    ctaHref: '/profile',
    priority: 'critical',
    allowedSurfaces: [...ALL_SURFACES],
    requiredTriggers: ['logged_in', 'profile_incomplete'],
  },
  add_profile_photo: {
    id: 'add_profile_photo',
    category: 'profile_completion',
    titleKey: 'activityCards.add_profile_photo.title',
    descriptionKey: 'activityCards.add_profile_photo.description',
    ctaKey: 'activityCards.add_profile_photo.cta',
    ctaKind: 'navigate',
    ctaHref: '/profile',
    priority: 'high',
    allowedSurfaces: [...ALL_SURFACES],
    requiredTriggers: ['logged_in', 'no_profile_photo'],
  },
  configure_accepted_values: {
    id: 'configure_accepted_values',
    category: 'profile_completion',
    titleKey: 'activityCards.configure_accepted_values.title',
    descriptionKey: 'activityCards.configure_accepted_values.description',
    ctaKey: 'activityCards.configure_accepted_values.cta',
    ctaKind: 'navigate',
    ctaHref: '/profile',
    priority: 'normal',
    allowedSurfaces: ['profile_owner', 'desktop_sidebar'],
    requiredTriggers: ['logged_in', 'is_seller', 'no_accepted_values'],
  },
  add_workspace_photos: {
    id: 'add_workspace_photos',
    category: 'profile_completion',
    titleKey: 'activityCards.add_workspace_photos.title',
    descriptionKey: 'activityCards.add_workspace_photos.description',
    ctaKey: 'activityCards.add_workspace_photos.cta',
    ctaKind: 'navigate',
    ctaHref: '/profile',
    priority: 'normal',
    allowedSurfaces: ['profile_owner', 'desktop_sidebar'],
    requiredTriggers: ['logged_in', 'has_seller_role'],
  },
  connect_stripe: {
    id: 'connect_stripe',
    category: 'profile_completion',
    titleKey: 'activityCards.connect_stripe.title',
    descriptionKey: 'activityCards.connect_stripe.description',
    ctaKey: 'activityCards.connect_stripe.cta',
    ctaKind: 'navigate',
    ctaHref: '/verkoper/instellingen',
    priority: 'high',
    allowedSurfaces: ['profile_owner', 'desktop_sidebar'],
    requiredTriggers: ['logged_in', 'is_seller', 'no_stripe_connected'],
  },
  set_location: {
    id: 'set_location',
    category: 'local_activation',
    titleKey: 'activityCards.set_location.title',
    descriptionKey: 'activityCards.set_location.description',
    ctaKey: 'activityCards.set_location.cta',
    ctaKind: 'navigate',
    ctaHref: '/profile',
    priority: 'critical',
    allowedSurfaces: [...ALL_SURFACES],
    requiredTriggers: ['logged_in', 'no_location'],
  },
  explore_nearby_requests: {
    id: 'explore_nearby_requests',
    category: 'local_activation',
    titleKey: 'activityCards.explore_nearby_requests.title',
    descriptionKey: 'activityCards.explore_nearby_requests.description',
    ctaKey: 'activityCards.explore_nearby_requests.cta',
    ctaKind: 'navigate',
    ctaHref: '/',
    priority: 'high',
    allowedSurfaces: FEED_SURFACES,
    requiredTriggers: ['logged_in', 'has_location', 'nearby_requests_available'],
  },
  invite_nearby: {
    id: 'invite_nearby',
    category: 'local_activation',
    titleKey: 'activityCards.invite_nearby.title',
    descriptionKey: 'activityCards.invite_nearby.description',
    ctaKey: 'activityCards.invite_nearby.cta',
    ctaKind: 'navigate',
    ctaHref: '/welkom',
    priority: 'normal',
    allowedSurfaces: FEED_SURFACES,
    requiredTriggers: ['logged_in', 'has_location'],
  },
};

export const ACTIVITY_CARD_IDS = Object.keys(
  ACTIVITY_CARD_REGISTRY,
) as ActivityCardId[];

export function getActivityCardDefinition(
  id: ActivityCardId,
): ActivityCardDefinition {
  return ACTIVITY_CARD_REGISTRY[id];
}

export function listActivityCardsByCategory(
  category: ActivityCardCategory,
): ActivityCardDefinition[] {
  return ACTIVITY_CARD_IDS.map((id) => ACTIVITY_CARD_REGISTRY[id]).filter(
    (c) => c.category === category,
  );
}
