/**
 * Phase 3 — Growth foundation public exports.
 * Readiness / documentation SSOT only.
 */

export {
  BUSINESS_ECOSYSTEM_FIT,
  BUYER_EXPERIENCE_READINESS,
  COMMUNITY_EXPERIENCE_READINESS,
  CREATOR_CRAFT_PATHS,
  CREATOR_EXPERIENCE_READINESS,
  GROWTH_CAMPAIGN_READINESS,
  GROWTH_FOUNDATION_OBJECTIVE,
  GROWTH_LOOPS,
  GROWTH_ROADMAP,
  GROWTH_SCORES,
  LOCAL_EXPANSION_READINESS,
  MARKETPLACE_ADOPTION_READINESS,
  REAL_WORLD_TRUST_READINESS,
  RETENTION_READINESS,
  growthFoundationBrief,
  type ReadinessItem,
  type ReadinessStatus,
} from './growth-foundation';
