-- AlterTable: publieke maker-contactvelden (opt-in, los van privé phoneNumber)
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "publicPhoneEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "publicPhoneNumber" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "publicWhatsappEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "publicWhatsappNumber" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "publicInstagramEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "instagramUrl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "publicFacebookEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "facebookUrl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "publicTikTokEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "tiktokUrl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "publicWebsiteEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "websiteUrl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "publicTelegramEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "telegramUrl" TEXT;
