export const DIAGNOSTIC_CODES = {
  OK: "AW.OK",
  FALLBACK_MISSING_PRIMARY: "AW.FALLBACK.MISSING_PRIMARY",
  FALLBACK_INVALID_POLICY: "AW.FALLBACK.INVALID_POLICY",
  UNKNOWN_WIDGET: "AW.REJECT.UNKNOWN_WIDGET",
  INCOMPATIBLE: "AW.REJECT.INCOMPATIBLE",
  INVALID_PIN: "AW.WARN.INVALID_PIN",
  INVALID_PREFS_VERSION: "AW.WARN.INVALID_PREFS_VERSION",
  COLLAPSED: "AW.FALLBACK.COLLAPSED",
  CAPACITY: "AW.REJECT.CAPACITY",
  FORBIDDEN_MODE: "AW.REJECT.FORBIDDEN_MODE",
  COMPAT_OFF: "AW.COMPAT.OFF",
  COMPAT_SHADOW: "AW.COMPAT.SHADOW",
  DUPLICATE_SEALED: "AW.HARD.DUPLICATE_SEALED",
  DUPLICATE_PRESERVATION_KEY: "AW.HARD.DUPLICATE_PRESERVATION_KEY",
  UNSUPPORTED_SCHEMA: "AW.HARD.UNSUPPORTED_SCHEMA",
  DOMAIN_FIELD_FORBIDDEN: "AW.HARD.DOMAIN_FIELD_FORBIDDEN",
  HEIGHT_DEMOTE: "AW.INFO.HEIGHT_DEMOTE",
  REDUCED_MOTION: "AW.INFO.REDUCED_MOTION",
} as const;

export type DiagnosticCode =
  (typeof DIAGNOSTIC_CODES)[keyof typeof DIAGNOSTIC_CODES];
